"""change payload to json

Revision ID: 0f821c0fce3e
Revises: ff3b6a9d2c4e
Create Date: 2026-01-17 12:58:36.635330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f821c0fce3e'
down_revision: Union[str, Sequence[str], None] = 'ff3b6a9d2c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
# 3. Alter the payload column with explicit casting
    # The 'postgresql_using' is critical for converting String -> JSONB
    op.alter_column('tasks', 'payload',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='payload::jsonb')

    # 4. Other auto-generated changes
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    
    # Use 'if exists' logic for the index to avoid crash if it's already gone
    op.execute("DROP INDEX IF EXISTS ix_tasks_status_scheduled_at")
    
    op.create_unique_constraint(None, 'users', ['username'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_tasks_status_scheduled_at'), 'tasks', ['status', 'scheduled_at'], unique=False)
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('tasks', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
